[terminal.shell]
program = "/usr/bin/zsh"
args = ["-c", "exec tmux new-session -A -s main"]

[font]
size = 11.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[colors.primary]
background = "#0a0a0a"
foreground = "#e4e4e7"

[colors.cursor]
text   = "#0a0a0a"
cursor = "#e4e4e7"

[colors.selection]
text       = "#0a0a0a"
background = "#e4e4e7"

# Todas as 16 cores mapeadas para cinza
[colors.normal]
black   = "#18181b"
red     = "#3f3f46"
green   = "#52525b"
yellow  = "#71717a"
blue    = "#52525b"
magenta = "#52525b"
cyan    = "#71717a"
white   = "#a1a1aa"

[colors.bright]
black   = "#27272a"
red     = "#52525b"
green   = "#71717a"
yellow  = "#a1a1aa"
blue    = "#71717a"
magenta = "#71717a"
cyan    = "#a1a1aa"
white   = "#e4e4e7"

[window]
padding = { x = 10, y = 10 }
decorations = "None"

[scrolling]
history = 10000

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"
