# Teclado: layout brasileiro (ThinkPad ABNT2)
input type:keyboard {
    xkb_layout br
    xkb_variant thinkpad
    xkb_options grp:alt_shift_toggle,caps:swapescape
}

# Cursor branco com contraste
seat * xcursor_theme DMZ-White 24

# Touchpad: habilita tap para clicar e scroll natural
input type:touchpad {
    tap enabled
    natural_scroll enabled
    dwt enabled
}
