# Fundo sólido — cinza escuro
output * bg #3f3f3f solid_color

# Bordas de janela — preto/cinza puro, sem cores
# focused: border background text indicator child_border
client.focused          #27272a #111111 #e4e4e7 #3f3f46 #27272a
client.focused_inactive #18181b #0a0a0a #3f3f46 #18181b #18181b
client.unfocused        #111111 #0a0a0a #27272a #111111 #111111
client.urgent           #3f3f46 #111111 #a1a1aa #3f3f46 #3f3f46

# Espessura da borda
default_border          pixel 1
default_floating_border pixel 1

# Gaps
gaps inner 6
gaps outer 0
