# Print: seleciona área e copia direto para o clipboard
bindsym {
    Print             exec grimshot --notify copy area
    Alt+Print         exec grimshot --notify copy active
    Ctrl+Print        exec grimshot --notify copy output
    Shift+Print       exec grimshot --notify save output
}
