set $mode_power (l) lock  (e) logout  (u) suspend  (r) reboot  (s) shutdown  (Esc) cancel

mode "$mode_power" {
    bindsym l exec swaylock, mode "default"
    bindsym e exec swaymsg exit
    bindsym u exec systemctl suspend, mode "default"
    bindsym r exec systemctl reboot
    bindsym s exec systemctl poweroff
    bindsym Escape mode "default"
    bindsym Return mode "default"
}

unbindsym $mod+Shift+e
bindsym $mod+Shift+e mode "$mode_power"
