# Sobrescreve /usr/share/sway/config.d/90-swayidle.conf
# Dim 30s antes de travar, depois trava, depois desliga display

exec swayidle -w \
    timeout 270  'brightnessctl -s set 10%' \
    timeout 300  'brightnessctl -r; swaylock -f' \
    resume       'brightnessctl -r' \
    timeout 600  'swaymsg "output * power off"' \
    resume       'swaymsg "output * power on"' \
    timeout 1200 '[ "$(cat /sys/class/power_supply/AC/online)" = "0" ] && systemctl suspend' \
    before-sleep 'swaylock -f' \
    lock         'swaylock -f' \
    unlock       'pkill -xu "$USER" -SIGUSR1 swaylock'
