# Inicia o gnome-keyring-daemon e exporta as variáveis para a sessão
exec eval $(/usr/bin/gnome-keyring-daemon --start --daemonize --components=pkcs11,secrets,ssh) && \
     /usr/bin/dbus-update-activation-environment --systemd GNOME_KEYRING_CONTROL GNOME_KEYRING_PID SSH_AUTH_SOCK
